/**
 * Loads the settings module with a mocked config.json. The file is generated by the SDK and does
 * not exist in the repository, so the mock has to be virtual.
 * @param {Object} config The content of the generated config.json.
 * @returns {Object} The exports of the settings module.
 */
const loadSettings = (config) => {
  jest.resetModules();
  jest.doMock('./config.json', () => config, { virtual: true });

  // eslint-disable-next-line global-require
  return require('./settings');
};

describe('settings', () => {
  afterEach(() => {
    jest.resetModules();
  });

  it('should fall back to defaults for an empty config', () => {
    const { settings, isWidgetScriptNeeded } = loadSettings({});

    expect(settings).toEqual({
      productReviewWidgetId: '',
      shopReviewsWidgetId: '',
      showProductReviews: true,
      showRatingValue: false,
      showRatingValueInLists: false,
      identifierType: 'sku',
      identifierSource: 'identifiers.sku',
    });
    expect(isWidgetScriptNeeded).toBe(false);
  });

  it('should fall back to defaults for unsupported values', () => {
    const { settings } = loadSettings({
      productIdentifierType: 'ean',
      productIdentifierSource: 'identifiers.upc',
    });

    expect(settings.identifierType).toBe('sku');
    expect(settings.identifierSource).toBe('identifiers.sku');
  });

  it('should take over a complete config', () => {
    const { settings, isWidgetScriptNeeded } = loadSettings({
      productReviewWidgetId: ' wdg-1 ',
      shopReviewsWidgetId: 'wdg-2',
      showProductReviews: false,
      showRatingValue: false,
      showRatingValueInLists: false,
      productIdentifierType: 'gtin',
      productIdentifierSource: 'identifiers.ean',
    });

    expect(settings).toEqual({
      productReviewWidgetId: 'wdg-1',
      shopReviewsWidgetId: 'wdg-2',
      showProductReviews: false,
      showRatingValue: false,
      showRatingValueInLists: false,
      identifierType: 'gtin',
      identifierSource: 'identifiers.ean',
    });
    expect(isWidgetScriptNeeded).toBe(true);
  });

  it('should not need the script when the only widget sits behind switched off reviews', () => {
    const { isWidgetScriptNeeded } = loadSettings({
      productReviewWidgetId: 'wdg-1',
      showProductReviews: false,
      showRatingValue: false,
      showRatingValueInLists: false,
    });

    expect(isWidgetScriptNeeded).toBe(false);
  });
});
