import React from 'react';
import { shallow } from 'enzyme';

const PRODUCT_ID = 'product-1';

// jest hoists the mock factories above the module scope, so the variables they read have to be
// prefixed with "mock".
let mockProduct = null;
let mockHasReviews = true;

jest.mock('react-redux', () => ({
  useSelector: selector => selector({}),
}));

jest.mock('@shopgate/engage/product', () => ({
  getProductDataById: () => mockProduct,
}));

jest.mock('@shopgate/engage/core', () => ({
  useCurrentProduct: () => ({ productId: PRODUCT_ID }),
}));

jest.mock('@shopgate/engage/core/helpers', () => ({
  i18n: {
    number: (value, fractions) => value.toFixed(fractions).replace('.', ','),
  },
}));

jest.mock('@shopgate/engage/components', () => {
  // A shallow render does not render the mock itself, so it is found by its display name.
  const RatingStars = () => null;
  RatingStars.displayName = 'RatingStars';

  return { RatingStars };
});

jest.mock('@shopgate/pwa-common/helpers/config', () => ({
  __esModule: true,
  default: { get hasReviews() { return mockHasReviews; } },
  themeConfig: { colors: { shade3: '#9a9a9a' } },
}));

// makeStyles builds on emotion, whose hooks do not survive a shallow render outside of the theme.
jest.mock('@shopgate/engage/styles', () => ({
  makeStyles: () => () => () => ({
    classes: {},
    cx: (...names) => names.filter(Boolean).join(' '),
  }),
}));

/**
 * Loads the portal with a mocked config.json. The file is generated by the SDK and does not exist
 * in the repository, so the mock has to be virtual.
 * @param {Object} config The content of the generated config.json.
 * @returns {React.ComponentType} The portal component.
 */
const loadPortal = (config) => {
  jest.resetModules();
  jest.doMock('../../config.json', () => config, { virtual: true });

  // eslint-disable-next-line global-require
  return require('./index').default;
};

const children = <div className="original" />;

describe('<ProductRating />', () => {
  beforeEach(() => {
    mockProduct = {
      rating: {
        average: 96.6,
        count: 18,
        reviewCount: 18,
      },
    };
    mockHasReviews = true;
  });

  afterEach(() => {
    jest.resetModules();
  });

  it('should keep the rating of the theme while the value is switched off', () => {
    const ProductRating = loadPortal({});
    const wrapper = shallow(<ProductRating>{children}</ProductRating>);

    expect(wrapper.find('.original')).toHaveLength(1);
  });

  it('should show the stars, the average with two decimals and the count in brackets', () => {
    const ProductRating = loadPortal({ showRatingValue: true });
    const wrapper = shallow(<ProductRating>{children}</ProductRating>);

    expect(wrapper.find('RatingStars').prop('value')).toBe(96.6);
    expect(wrapper.find('.trusted-shops-reviews__rating-value').text()).toBe('4,83');
    expect(wrapper.find('.trusted-shops-reviews__rating-count').text()).toBe('(18)');
  });

  it('should keep the rating of the theme for a product without ratings', () => {
    mockProduct = {
      rating: {
        average: 0,
        count: 0,
        reviewCount: 0,
      },
    };

    const ProductRating = loadPortal({ showRatingValue: true });
    const wrapper = shallow(<ProductRating>{children}</ProductRating>);

    expect(wrapper.find('.original')).toHaveLength(1);
  });

  it('should keep out of the way when the app has no reviews at all', () => {
    mockHasReviews = false;

    const ProductRating = loadPortal({ showRatingValue: true });
    const wrapper = shallow(<ProductRating>{children}</ProductRating>);

    expect(wrapper.find('.original')).toHaveLength(1);
  });
});
