import React from 'react';
import { shallow } from 'enzyme';

const PRODUCT_ID = 'product-1';

// jest hoists the mock factory above the module scope, so the variable it reads has to be
// prefixed with "mock".
let mockProduct = null;
let mockBaseProduct = null;

jest.mock('react-redux', () => ({
  useSelector: selector => selector({}),
}));

jest.mock('@shopgate/engage/product', () => ({
  getProductDataById: (state, { productId }) => (
    productId === PRODUCT_ID ? mockProduct : mockBaseProduct
  ),
}));

// makeStyles builds on emotion, whose hooks do not survive a shallow render outside of the theme.
// The class names are irrelevant here - what the component renders is what these tests check.
jest.mock('@shopgate/engage/styles', () => ({
  makeStyles: () => () => () => ({ classes: {} }),
}));

/**
 * Loads the portal with a mocked config.json. The file is generated by the SDK and does not exist
 * in the repository, so the mock has to be virtual.
 * @param {Object} config The content of the generated config.json.
 * @returns {React.ComponentType} The portal component.
 */
const loadPortal = (config) => {
  jest.resetModules();
  jest.doMock('../../config.json', () => config, { virtual: true });

  // eslint-disable-next-line global-require
  return require('./index').default;
};

const configured = {
  productReviewWidgetId: 'wdg-1',
  showProductReviews: true,
  productIdentifierType: 'sku',
  productIdentifierSource: 'identifiers.sku',
};

const children = <div className="original" />;

describe('<ProductReviews />', () => {
  beforeEach(() => {
    mockBaseProduct = null;
    mockProduct = {
      id: PRODUCT_ID,
      identifiers: {
        sku: 'SKU-4711',
      },
      rating: {
        average: 94.6,
        count: 41,
        reviewCount: 41,
      },
    };
  });

  afterEach(() => {
    jest.resetModules();
  });

  it('should render the Trusted Shops widget for a product with reviews', () => {
    const ProductReviews = loadPortal(configured);
    const wrapper = shallow(<ProductReviews productId={PRODUCT_ID}>{children}</ProductReviews>);

    const widget = wrapper.find('EtrustedWidget');

    expect(wrapper.find('#reviewsExcerpt').exists()).toBe(true);
    expect(widget.prop('widgetId')).toBe('wdg-1');
    expect(widget.prop('identifier')).toBe('SKU-4711');
    expect(widget.prop('identifierType')).toBe('sku');
  });

  it('should address the widget with the main product of a variant', () => {
    // The page that lists all reviews takes its product from the route, which can be a variant.
    mockProduct = {
      ...mockProduct,
      baseProductId: 'base-1',
    };
    mockBaseProduct = {
      id: 'base-1',
      identifiers: {
        sku: 'SKU-4711-M',
      },
    };

    const ProductReviews = loadPortal(configured);
    const wrapper = shallow(<ProductReviews productId={PRODUCT_ID}>{children}</ProductReviews>);

    expect(wrapper.find('EtrustedWidget').prop('identifier')).toBe('SKU-4711-M');
  });

  it('should fall back to the variant when its main product is not loaded', () => {
    mockProduct = {
      ...mockProduct,
      baseProductId: 'base-1',
    };

    const ProductReviews = loadPortal(configured);
    const wrapper = shallow(<ProductReviews productId={PRODUCT_ID}>{children}</ProductReviews>);

    expect(wrapper.find('EtrustedWidget').prop('identifier')).toBe('SKU-4711');
  });

  it('should render nothing when the reviews are switched off', () => {
    const ProductReviews = loadPortal({
      ...configured,
      showProductReviews: false,
    });
    const wrapper = shallow(<ProductReviews productId={PRODUCT_ID}>{children}</ProductReviews>);

    expect(wrapper).toBeEmptyRender();
  });

  it('should keep the reviews of the shop when no widget is configured', () => {
    const ProductReviews = loadPortal({
      ...configured,
      productReviewWidgetId: '',
    });
    const wrapper = shallow(<ProductReviews productId={PRODUCT_ID}>{children}</ProductReviews>);

    expect(wrapper.find('.original').exists()).toBe(true);
  });

  it('should keep the reviews of the shop for a product without an identifier', () => {
    mockProduct = {
      id: PRODUCT_ID,
      rating: {
        average: 0,
        count: 0,
        reviewCount: 0,
      },
    };

    const ProductReviews = loadPortal(configured);
    const wrapper = shallow(<ProductReviews productId={PRODUCT_ID}>{children}</ProductReviews>);

    expect(wrapper.find('.original').exists()).toBe(true);
  });

  it('should leave hiding an empty widget to Trusted Shops', () => {
    // A rating count of null is what the shop delivers when the backend step has not replaced the
    // rating. Hiding the widget here would hide real Trusted Shops reviews.
    mockProduct.rating = {
      average: 0,
      count: null,
      reviewCount: null,
    };

    const ProductReviews = loadPortal(configured);
    const wrapper = shallow(<ProductReviews productId={PRODUCT_ID}>{children}</ProductReviews>);

    expect(wrapper.find('EtrustedWidget').exists()).toBe(true);
  });
});
