import React from 'react';
import { shallow } from 'enzyme';

/**
 * Loads the widget with a mocked config.json. The file is generated by the SDK and does not exist
 * in the repository, so the mock has to be virtual.
 * @param {Object} config The content of the generated config.json.
 * @returns {React.ComponentType} The widget component.
 */
const loadWidget = (config) => {
  jest.resetModules();
  jest.doMock('../../config.json', () => config, { virtual: true });

  // eslint-disable-next-line global-require
  return require('./index').default;
};

describe('<ShopReviews />', () => {
  afterEach(() => {
    jest.resetModules();
  });

  it('should render nothing when no widget id is known at all', () => {
    const ShopReviews = loadWidget({});

    expect(shallow(<ShopReviews settings={{}} />).isEmptyRender()).toBe(true);
  });

  it('should use the widget id of the extension configuration', () => {
    const ShopReviews = loadWidget({ shopReviewsWidgetId: 'wdg-config' });

    expect(shallow(<ShopReviews settings={{}} />).prop('widgetId')).toBe('wdg-config');
  });

  it('should let a widget instance point at a different widget', () => {
    const ShopReviews = loadWidget({ shopReviewsWidgetId: 'wdg-config' });
    const wrapper = shallow(<ShopReviews settings={{ widgetId: 'wdg-instance' }} />);

    expect(wrapper.prop('widgetId')).toBe('wdg-instance');
  });

  it('should work without any extension configuration, on the widget id alone', () => {
    const ShopReviews = loadWidget({});
    const wrapper = shallow(<ShopReviews settings={{ widgetId: 'wdg-instance' }} />);

    expect(wrapper.prop('widgetId')).toBe('wdg-instance');
  });
});
